"""Exploratory analysis of normalized study-posting audit reports."""

from study_posting_audit_exploration.aggregation import (
    build_attempt_analysis_tables,
    build_attempt_start_experience_summary,
    build_author_analysis_tables,
    build_author_handoff_summary,
    build_compensation_analysis_summary,
    build_content_source_concordance_matrix,
    build_content_source_concordance_summary,
    build_current_author_experience_summary,
    build_field_adoption_editing_summary,
    build_field_analysis_tables,
    build_grouped_attempt_summary,
    build_grouped_author_summary,
    build_grouped_study_summary,
    build_nontext_field_adoption_summary,
    build_overview_summary,
    build_overview_tables,
    build_study_analysis_tables,
    build_study_attempt_history_summary,
    build_suggestion_selection_summary,
)
from study_posting_audit_exploration.config import (
    ExplorationInputConfig,
    ExplorationRunConfig,
)
from study_posting_audit_exploration.derivation import (
    EDIT_INTENSITY_THRESHOLD_SCHEME,
    AppointmentQualityFinding,
    author_changed,
    classify_edit_intensity,
    derive_appointments,
    derive_attempt_histories,
    derive_completed_ai_field_analysis,
    derive_completed_ai_readability_pairs,
    derive_role_columns,
    effective_author_role,
    same_author_within_study,
)
from study_posting_audit_exploration.errors import (
    AuditExplorationError,
    ExplorationConfigurationError,
    ExplorationInputError,
    ExplorationValidationError,
)
from study_posting_audit_exploration.loading import load_audit_report
from study_posting_audit_exploration.models import (
    AttemptAnalysisTables,
    AttemptHistoryTables,
    AuthorAnalysisTables,
    DescriptiveStatistics,
    ExplorationPublication,
    FieldAnalysisTables,
    LoadedAuditReport,
    OverviewTables,
    StudyAnalysisTables,
    ValidationSummary,
)
from study_posting_audit_exploration.publication import publish_exploration
from study_posting_audit_exploration.statistics import describe_numeric
from study_posting_audit_exploration.validation import validate_audit_report

__version__ = "0.1.0"

__all__ = [
    "EDIT_INTENSITY_THRESHOLD_SCHEME",
    "AppointmentQualityFinding",
    "AttemptAnalysisTables",
    "AttemptHistoryTables",
    "AuditExplorationError",
    "AuthorAnalysisTables",
    "DescriptiveStatistics",
    "ExplorationConfigurationError",
    "ExplorationInputConfig",
    "ExplorationInputError",
    "ExplorationPublication",
    "ExplorationRunConfig",
    "ExplorationValidationError",
    "FieldAnalysisTables",
    "LoadedAuditReport",
    "OverviewTables",
    "StudyAnalysisTables",
    "ValidationSummary",
    "__version__",
    "author_changed",
    "build_attempt_analysis_tables",
    "build_attempt_start_experience_summary",
    "build_author_analysis_tables",
    "build_author_handoff_summary",
    "build_compensation_analysis_summary",
    "build_content_source_concordance_matrix",
    "build_content_source_concordance_summary",
    "build_current_author_experience_summary",
    "build_field_adoption_editing_summary",
    "build_field_analysis_tables",
    "build_grouped_attempt_summary",
    "build_grouped_author_summary",
    "build_grouped_study_summary",
    "build_nontext_field_adoption_summary",
    "build_overview_summary",
    "build_overview_tables",
    "build_study_analysis_tables",
    "build_study_attempt_history_summary",
    "build_suggestion_selection_summary",
    "classify_edit_intensity",
    "derive_appointments",
    "derive_attempt_histories",
    "derive_completed_ai_field_analysis",
    "derive_completed_ai_readability_pairs",
    "derive_role_columns",
    "describe_numeric",
    "effective_author_role",
    "load_audit_report",
    "publish_exploration",
    "same_author_within_study",
    "validate_audit_report",
]
